apiVersion: v1
kind: ServiceAccount
metadata:
  name: careerhub-secrets-reader
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: careerhub-secret-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef: # IRSA 연결한 ServiceAccount
            name: careerhub-secrets-reader
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: review-mongodb
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: review-mongodb
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/review-service/mongodb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: posting-mongodb
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: posting-mongodb
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/posting-service/mongodb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: userinfo-mongodb
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: userinfo-mongodb
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/userinfo-service/mongodb
