apiVersion: v1
kind: ServiceAccount
metadata:
  name: careerhub-secrets-reader
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: careerhub-secret-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef: # IRSA 연결한 ServiceAccount
            name: careerhub-secrets-reader
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: review-mongodb
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: system-cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: review-mongodb
  dataFrom:
    - key: /prod-eks/careerhub/prod/review-service/mongodb
