apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: bootstrap-system
            path: bootstrap-system
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: root
              operator: In
              values: ["bootstrap-system"]
  template:
    metadata:
      name: "{{.name}}"
      labels:
        root: "{{.name}}"
    spec:
      project: root
      source:
        repoURL: git@github.com:jyoliar-careerhub/k8s-config.git
        targetRevision: feature/init-config
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 0 # ← 0이면 무제한 재시도
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
