apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-admin
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-parameter-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: mongodb-admin
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/mongodb/admin
