apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: careerhub
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators: []
  template:
    metadata:
      name: "{{.name}}"
      labels:
        careerhub/prod: "{{.name}}"
    spec:
      project: careerhub
      source:
        repoURL: git@github.com:jyoliar-careerhub/k8s-config.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 0 # ← 0이면 무제한 재시도
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
