apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::986069063944:role/prod-argocd-repo-reader"
  name: system-secret-reader
  namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: system-secretstore
  namespace: kube-system
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef: # IRSA 연결한 ServiceAccount
            name: system-secret-reader
