apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::986069063944:role/prod-system-secrets-reader"
  name: system-secrets-reader
  namespace: kube-system
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: system-cluster-secret-store
  namespace: kube-system
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef: # IRSA 연결한 ServiceAccount
            name: system-secrets-reader
            namespace: kube-system
