{{- $opensearch_name := .Values.opensearch.name -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
    [INPUT]
        Name              tail
        Tag               {{.Values.targetNamespace}}.*
        Exclude_Path      {{.Values.kubeLogsDir}}/{{.Values.name}}*_{{.Values.targetNamespace}}_*.log
        Path              {{.Values.kubeLogsDir}}/*_{{.Values.targetNamespace}}_*.log
        Parser            cri
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [FILTER]
        Name            parser
        Match           {{.Values.targetNamespace}}.*
        Key_Name        log
        Parser          json_log
        Parser          pass_through
        Reserve_Data    On
    [OUTPUT]
        Name            stdout
        Match           {{ $opensearch_name }}.*
    [OUTPUT]
        Name            opensearch
        Match           {{.Values.targetNamespace}}.*
        Host            {{ $opensearch_name }}
        Port            9200
        Include_Tag_Key On 
        tls.verify      Off
        tls             On
        HTTP_User       admin
        HTTP_Passwd     {{ .Values.initialAdminPassword }}
        Suppress_Type_Name  On
        Logstash_Format On
        Logstash_Prefix {{.Values.targetNamespace}}
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name        json_log
        Format      json
    [PARSER]
        Name        pass_through
        Format      regex
        Regex       ^(?<raw_log>.*)$