{{- $kube_logs_dir := .Values.kubeLogsDir -}}
{{- $opensearch_endpoint := .Values.opensearch.endpoint -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
    {{- range $ns := .Values.targetNamespaces }}
    [INPUT]
        Name              tail
        Tag               {{ $ns }}
        Path              {{$kube_logs_dir}}/*_{{ $ns }}_*.log
        Parser            cri
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    {{- end }}
    [FILTER]
        Name            parser
        Match           *
        Key_Name        log
        Parser          json_log
        Parser          pass_through
        Reserve_Data    On
    {{- range $ns := .Values.targetNamespaces }}
    [OUTPUT]
        Name            opensearch
        AWS_Auth        On
        AWS_Region      ${AWS_REGION}
        AWS_Service_Name aoss
        Match           {{ $ns }}
        Host            {{ $opensearch_endpoint }}
        Port            443
        Include_Tag_Key On 
        tls.verify      Off
        tls             On
        Suppress_Type_Name  On
        Logstash_Format On
        Logstash_Prefix {{ $ns }}
    {{- end }}
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name        json_log
        Format      json
    [PARSER]
        Name        pass_through
        Format      regex
        Regex       ^(?<raw_log>.*)$