{{- $name := .Values.fluentbit.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-opensearch-role #pod identity
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{$name}}
spec:
  selector:
    matchLabels:
      k8s-app: {{$name}}
  template:
    metadata:
      annotations:
        checksum/config: |
          {{ include (print $.Template.BasePath "/fluentbit_configmap.yaml") . | sha256sum }}
      labels:
        k8s-app: {{$name}}
    spec:
      serviceAccountName: fluentbit-opensearch-role
      containers:
        - name: {{$name}}
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.32.5.20250327
          imagePullPolicy: Always
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
