{{- $name := print .Values.name "-opensearch" -}}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  labels:
    k8s-app: {{$name}}
spec:
  selector:
    matchLabels:
      k8s-app: {{$name}}
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{$name}}
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range .Values.nodeSelector }}
        {{ .key }}: {{ .value }}
        {{- end }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
        {{- range .Values.tolerations }}
        - key: {{ .key }}
          operator: {{ .operator }}
          value: {{ .value }}
          effect: {{ .effect }}
        {{- end }}
    {{- end }}
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["chown", "-R", "1000:1000", "/usr/share/opensearch/data"]
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      containers:
        - name: {{$name}}
          image: opensearchproject/opensearch:latest
          env:
            - name: discovery.type
              value: single-node
            - name: node.name
              value: opensearch
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: "{{ .Values.initialAdminPassword }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: opensearch-data
          hostPath:
            path: /usr/share/opensearch/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}
  labels:
    k8s-app: {{$name}}
spec:
  type: ClusterIP
  selector:
    k8s-app: {{$name}}
  ports:
    - name: http
      port: 9200
      targetPort: 9200
