apiVersion: batch/v1
kind: CronJob
metadata:
  name: posting-skillscanner
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: posting-skillscanner
              image: "986069063944.dkr.ecr.ap-south-1.amazonaws.com/prod-posting-skillscanner-ecr:2025.05.13-05.16.50"
