apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: log-system
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
          - name: opensearch_volume
            path: system/log-system/opensearch_volume
          - name: opensearch_secret
            path: system/log-system/opensearch_secret
          - name: opensearch
            path: system/log-system/opensearch
          - name: fluentbit
            path: system/log-system/fluentbit
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: system/log-system
              operator: In
              values: ["opensearch_volume", "opensearch_secret"]
        - matchExpressions:
            - key: system/log-system
              operator: In
              values: ["opensearch"]
        - matchExpressions:
            - key: system/log-system
              operator: In
              values: ["fluentbit"]
  template:
    metadata:
      name: "{{.name}}"
      namespace: kube-logs
      labels:
        system/log-system: "{{.name}}"
    spec:
      project: system
      source:
        repoURL: git@github.com:jyoliar-careerhub/k8s-config.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 0 # ← 0이면 무제한 재시도
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
