name: log-system
targetNamespaces:
  - nginx-gateway

opensearch:
  name: opensearch
  endpoint: 7iaph5gw00c1t18f84.ap-south-1.aoss.amazonaws.com

fluentbit:
  name: fluentbit

kubeLogsDir: /var/log/containers
