apiVersion: v1
kind: ServiceAccount
metadata:
  name: careerhub-secrets-reader
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: careerhub-secret-store-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef: # IRSA 연결한 ServiceAccount
            name: careerhub-secrets-reader
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: review-mongodb
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-parameter-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: review-mongodb
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/review-service/mongodb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: posting-mongodb
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-parameter-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: posting-mongodb
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/posting-service/mongodb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: userinfo-mongodb
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-parameter-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: userinfo-mongodb
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/userinfo-service/mongodb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secretkey
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-parameter-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: jwt-secretkey
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/jwt-secretkey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-client-secret
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-parameter-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: google-client-secret
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/google-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-mysql
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-parameter-store
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: auth-mysql
  dataFrom:
    - extract:
        key: /prod-eks/careerhub/prod/auth-service/mysql
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: careerhub-secret-store-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef: # IRSA 연결한 ServiceAccount
            name: careerhub-secrets-reader
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-mysql-user
spec:
  secretStoreRef: # Secret을 가져올 SecretStore 작성
    name: careerhub-secret-store-secrets-manager
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: auth-mysql-user
  dataFrom:
    - extract:
        key: rds!cluster-f015e120-8b5f-44ff-9f52-be796b8e3d38
