apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: log-system
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
          - name: opensearch-volume
            path: envs/prod/system/log-system/opensearch-volume
          - name: opensearch-secret
            path: envs/prod/system/log-system/opensearch-secret
          - name: opensearch
            path: envs/prod/system/log-system/opensearch
          - name: fluentbit
            path: system/log-system/fluentbit
            helmValueFile: envs/prod/system/log-system/fluentbit/values.yaml
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: system/log-system
              operator: In
              values: ["opensearch-volume", "opensearch-secret"]
        - matchExpressions:
            - key: system/log-system
              operator: In
              values: ["opensearch"]
        - matchExpressions:
            - key: system/log-system
              operator: In
              values: ["fluentbit"]
  templatePatch: |
    {{- with .helmValueFile }}
    spec:
      source: 
        helm:
          valueFiles:
            - "{{.}}"
    {{- end }}
  template:
    metadata:
      name: "{{.name}}"
      labels:
        system/log-system: "{{.name}}"
    spec:
      project: system
      source:
        repoURL: git@github.com:jyoliar-careerhub/k8s-config.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-logs
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 0 # ← 0이면 무제한 재시도
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
