apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: careerhub-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "8.0.11"
  security:
    authentication:
      modes: ["SCRAM"]
    roles: # custom roles are defined here
      - role: testRole
        db: admin
        privileges:
          - resource:
              db: "test"
              collection: "" # an empty string indicates any collection
            actions:
              - find
        roles: []
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: testRole # apply the custom role to the user
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume # volumeMounts.name과 동일해야 함
          spec:
            accessModes: ["ReadWriteOnce"] # RWO, RWX, ROX 등
            resources:
              requests:
                storage: 30Gi # 요청 용량
            volumeMode: Filesystem # 또는 Block
        - metadata:
            name: logs-volume # volumeMounts.name과 동일해야 함
          spec:
            accessModes: ["ReadWriteOnce"] # RWO, RWX, ROX 등
            resources:
              requests:
                storage: 5Gi # 요청 용량
            volumeMode: Filesystem # 또는 Block
      template:
        metadata:
          labels:
            scheduling.mongodb.com/cluster: careerhub
        spec:
          tolerations:
            - key: "app"
              operator: "Equal"
              value: "mongodb"
              effect: "NoSchedule"
          nodeSelector:
            app: mongodb
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - mongodb
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      scheduling.mongodb.com/cluster: careerhub
                  topologyKey: kubernetes.io/hostname
