kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-appdb
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-appdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-appdb
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb-kubernetes-database-pods
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb-kubernetes-appdb
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb-kubernetes-ops-manager
