kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb-kubernetes-database-pods
  namespace: <namespace>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb-kubernetes-appdb
  namespace: <namespace>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb-kubernetes-ops-manager
  namespace: <namespace>
