apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../careerhub/web

patches:
  - path: api-composer-patch.yaml
  - path: auth-service-patch.yaml
  - path: frontend-patch.yaml
  - path: httproute-patch.yaml
