apiVersion: apps/v1
kind: Deployment
metadata:
  name: posting-service
spec:
  template:
    spec:
      containers:
        - name: posting-service
          image: "986069063944.dkr.ecr.ap-south-1.amazonaws.com/prod-posting-service-ecr:2025.05.11-09.49.38"
