apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-service
spec:
  template:
    spec:
      containers:
        - name: userinfo-service
          image: "986069063944.dkr.ecr.ap-south-1.amazonaws.com/prod-userinfo-service-ecr:2025.05.13-05.15.15"
