apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-kubernetes-operator
  namespace: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb-kubernetes-operator
          env:
            - name: WATCH_NAMESPACE
              value: "*"
