apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: careerhub
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
          - name: careerhub-mongodb
            path: envs/dev/careerhub/mongodb
            namespace: mongodb
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: careerhub
              operator: In
              values: ["careerhub-mongodb"]
  templatePatch: |
    {{- with .namespace }}
    spec:
      destination:
        namespace: "{{.}}"
    {{- end }}
  template:
    metadata:
      name: "{{.name}}"
      labels:
        careerhub: "{{.name}}"
    spec:
      project: careerhub
      source:
        repoURL: git@github.com:jyoliar-careerhub/k8s-config.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: dev-careerhub
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 0 # ← 0이면 무제한 재시도
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
