apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.14.9
  - httproute.yaml
#patchesStrategicMerge:

patches:
  - path: argocd-server-configmap-patch.yaml
