apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::986069063944:role/prod-posting-service"
  name: posting-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posting-service
  template:
    metadata:
      labels:
        app: posting-service
    spec:
      serviceAccountName: posting-service
      restartPolicy: Always
      containers:
        - name: posting-service
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: posting-mongodb
                  key: endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: posting-mongodb
                  key: database
          envFrom:
            - configMapRef:
                name: posting-service-config
