apiVersion: v1
kind: ConfigMap
metadata:
  name: review-service-config
  labels:
    app: review-service
data:
  RESTAPI_GRPC_PORT: "50051"
  RESTAPI_GRPC_ENDPOINT: "review-service:50051"

  CRAWLER_GRPC_PORT: "50052"
  PROVIDER_GRPC_PORT: "50053"
  MONGO_AUTH_MECHANISM: "MONGODB-AWS"
  MONGO_AUTH_SOURCE: "$external"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::986069063944:role/prod-review-service"
  name: review-service
  labels:
    app: review-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  labels:
    app: review-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      serviceAccountName: review-service
      restartPolicy: Always
      containers:
        - name: review-service
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: review-mongodb
                  key: endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: review-mongodb
                  key: database
          envFrom:
            - configMapRef:
                name: review-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  labels:
    app: review-service
spec:
  type: ClusterIP
  ports:
    - name: restapi-grpc
      port: 50051
      targetPort: 50051
    - name: crawler-grpc
      port: 50052
      targetPort: 50052
    - name: provider-grpc
      port: 50053
      targetPort: 50053
  selector:
    app: review-service
