apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::986069063944:role/prod-userinfo-service"
  name: userinfo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userinfo-service
  template:
    metadata:
      labels:
        app: userinfo-service
    spec:
      serviceAccountName: userinfo-service
      restartPolicy: Always
      containers:
        - name: userinfo-service
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: userinfo-mongodb
                  key: endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: userinfo-mongodb
                  key: database
          envFrom:
            - configMapRef:
                name: userinfo-service-config
